// TO DO: Add array to store data from Firebase

var problem_list = [
    {
        agent_1_src: 'asset/avatar2.png',
        agent_1_statement: '',
        agent_2_src: 'asset/avatar1.png',
        agent_2_statement: 'You’ve started treatment',
        answerkey: 'Simple',
        condition: 'Fall 2019 User Testing',
        feedback_neg: "This statement is not a complex reflection. 'You’ve started treatment' is a straightforward restatement of the first part of what the client said. Little to no meaning has been added. The therapist could have said 'You’ve come to see me' and it would be a simple reflection of a different part of the statement.",
        feedback_pos: "You correctly identified this statement as a simple reflection. 'You’ve started treatment' is a straightforward restatement of the first part of what the client said. Little to no meaning has been added. The therapist could have said 'You’ve come to see me' and it would be a simple reflection of a different part of the statement.",
        hint_1: 'Simple reflections typically add little or no meaning to what the client said. You have decided to take your medication.',
        hint_2: 'Simple reflections do not emphasize what the client said. So you saw me right after taking your medication for a few days.',
        hint_3: 'Simple reflections make slight alterations to what the client said. For instance, so you only started taking your medication not long ago.',
        instruction: "Let's say that your client says 'I was taking medication for a few days and then I saw you'. Below you will be provided with a therapist reflection. Please categorize whether the reflection is simple or complex.",
        instructor: 'Eric Poitras',
        item: '8jskki',
        item_1_label: 'Simple',
        item_2_label: 'Complex',
        item_3_label: '',
        item_4_label: '',
        module: 'Categorize Reflection',
        session: 'd5te32',
        type: 'TrueFalse',
        validation: 'Please choose a response to the client before moving to the next step.',
        kc: 'reflection'
    },
    {
        agent_1_src: 'asset/avatar1.png',
        agent_1_statement: '',
        agent_2_src: 'asset/avatar2.png',
        agent_2_statement: 'I’m feeling tired',
        answerkey: 'You’re just worn out',
        condition: 'Fall 2019 User Testing',
        feedback_neg: "This therapist response is not a reflection. 'You’re just worn out' is a reflective statement.  The therapist is communicating back to the client that they heard what they said, and amplifying it slightly. The other two statements are questions asking about other symptoms or details. There are many other potential reflections, 'You’re just worn out', 'You didn’t sleep much', etc. They reflections may very in the extent to which the therapist stays close to exactly what the client sad or makes guesses about what might be going on.",
        feedback_pos: "You correctly identified the reflection. 'You’re just worn out' is a reflective statement.  The therapist is communicating back to the client that they heard what they said, and amplifying it slightly. The other two statements are questions asking about other symptoms or details. There are many other potential reflections, 'You’re just worn out', 'You didn't sleep much', etc. They reflections may very in the extent to which the therapist stays close to exactly what the client sad or makes guesses about what might be going on.",
        hint_1: 'You might come alongside a client by saying that it really may be too difficult for you.',
        hint_2: "You might try something like perhaps it's better to stay as is",
        hint_3: 'Try to emphasize slightly what the client said, like for instance, you seem to be worn out.',
        instruction: "Use just a bit of amplification to join with the person. The following are potential responses to a client's statement. After reading the client statement pick the therapist statement that is a reflection.",
        instructor: 'Eric Poitras',
        item: '2jdhg83',
        item_1_label: 'You’re just worn out',
        item_2_label: 'How did you sleep last night',
        item_3_label: 'Are you taking your medication',
        item_4_label: 'That is terrible, why do you think that is?',
        module: 'Identify Reflection',
        session: 'd5te32',
        type: 'Multi',
        validation: 'Please choose a response to the client before moving to the next step.',
        kc: 'reflection'
    },
    {
        agent_1_src: 'asset/avatar1.png',
        agent_1_statement: "It just seems like I don't have a lot of time to do it",
        agent_2_src: 'asset/avatar2.png',
        agent_2_statement: 'What is the thing that’s stopping you?',
        answerkey: 'Reflection',
        condition: 'Fall 2019 User Testing',
        feedback_neg: "Our computer does not think this statement was a reflection. Bummer. Of course, its just a machine, so click on the flag above if you think we made an error. In case it's helpful, here are a few examples of other ways you could have responded with reflections: A Reflection might be You don’t have a lot of time, or... You’re worried about doing a good job.",
        feedback_pos: "Our computer model thinks this was a reflection! Good work. Of course, it's just a machine, so click on the flag above if you think we made an error. In case it's helpful, here are a few examples of other ways you could have responded with reflections: A Reflection might be You don’t have a lot of time, or... You’re worried about doing a good job.",
        hint_1: 'Is that really the only reason why you’re here?',
        hint_2: 'How busy are you really?',
        hint_3: 'What are all these other things that take up so much of your time?',
        instruction: "Amplify client statements in an exagerated way (over or under). This encourages the client to argue less, and can elicit the other side of the client's ambivalence. The following is a client statement followed by a question from the therapist. For each statement, rewrite the question the therapist asks as a reflection.",
        instructor: 'Eric Poitras',
        item: '4tgad7',
        item_1_label: "",
        item_2_label: '',
        item_3_label: '',
        item_4_label: '',
        module: 'Elaborate Reflection',
        session: 'd5te32',
        type: 'Open',
        validation: 'Please write a response to the client before moving to the next step.',
        kc: 'reflection'
    }
];

var problem = {
    agent_1_src: '',
    agent_1_statement: '',
    agent_2_src: '',
    agent_2_statement: '',
    answerkey: '',
    condition: '',
    feedback_neg: '',
    feedback_pos: '',
    hint_1: '',
    hint_2: '',
    hint_3: '',
    instruction: '',
    instructor: '',
    item: '',
    item_1_label: '',
    item_2_label: '',
    item_3_label: '',
    item_4_label: '',
    module: '',
    session: '',
    type: '',
    validation: '',
    kc: ''
}

var log_list = [
    {
    attempt: 0,
    hint_request: 1,
    condition: 'Fall 2019 User Testing',
    elapsedtime: 984778,
    evaluation: 'incorrect',
    item: '2effw3',
    kc: 'reflection',
    module: 'Identify Reflection',
    qualifier: '',
    response: 'It sounds like you are tired.',
    session: 'uob30q',
    step: 0,
    student: 'Eric Poitras',
    time: '1563480693788'
    },
    {
    attempt: 0,
    hint_request: 0,
    condition: 'Fall 2019 User Testing',
    elapsedtime: 484778,
    evaluation: 'correct',
    item: '23rfs4',
    kc: 'reflection',
    module: 'Categorize Reflection',
    qualifier: '',
    response: 'Simple',
    session: 'uob03q',
    step: 0,
    student: 'Eric Poitras',
    time: '1563480693788'
    },
    {
    attempt: 0,
    hint_request: 0,
    condition: 'Fall 2019 User Testing',
    elapsedtime: 484778,
    evaluation: 'correct',
    item: '23fsad',
    kc: 'reflection',
    module: 'Categorize Reflection',
    qualifier: '',
    response: 'Complex',
    session: 'uob03q',
    step: 3,
    student: 'Eric Poitras',
    time: '1563480693788'
    },
    {
    attempt: 0,
    hint_request: 0,
    condition: 'Fall 2019 User Testing',
    elapsedtime: 484778,
    evaluation: 'correct',
    item: '23fsad',
    kc: 'reflection',
    module: 'Elaborate Reflection',
    qualifier: 'I think you should rethink your approach.',
    response: 'complex_reflection',
    session: 'uob03q',
    step: 4,
    student: 'Eric Poitras',
    time: '1563480693788'
    },
    {
    attempt: 0,
    hint_request: 0,
    condition: 'Fall 2019 User Testing',
    elapsedtime: 484778,
    evaluation: 'incorrect',
    item: '23fsad',
    kc: 'reflection',
    module: 'Elaborate Reflection',
    qualifier: 'I think we should talk about it.',
    response: 'simple_reflection',
    session: 'uob03q',
    step: 4,
    student: 'Eric Poitras',
    time: '1563480693788'
    }
];

var log = {
    attempt: 0,
    hint_request: 0,
    condition: '',
    elapsedtime: 0,
    evaluation: '',
    item: '',
    kc: '',
    module: '',
    qualifier: '',
    response: '',
    session: '',
    step: 0,
    student: '',
    time: ''
}